<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AwesomeAssertions" />
        <PackageReference Include="AwesomeAssertions.Json" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Reqnroll.NUnit" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\App\Study.App.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Reqnroll" />
        <Using Include="NUnit.Framework" />
    </ItemGroup>
</Project>
