<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AwesomeAssertions" />
        <PackageReference Include="AwesomeAssertions.Json" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Reqnroll.NUnit" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="Selenium.Support" />
        <PackageReference Include="Selenium.WebDriver" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\App\Study.App.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Reqnroll" />
        <Using Include="NUnit.Framework" />
    </ItemGroup>

    <ItemGroup>
      <ReqnrollFeatureFile Update="Features\Home.feature">
        <NormalizedLogicalName>Features/Search.feature</NormalizedLogicalName>
        <NormalizedRelativeDir>Features/</NormalizedRelativeDir>
        <CodeBehindFile>Features/Search.feature.cs</CodeBehindFile>
        <MessagesFile>obj\Debug/net10.0/Features/Search.feature.ndjson</MessagesFile>
        <MessagesResourceName>Features/Search.feature.ndjson</MessagesResourceName>
        <FeatureFileResourceName>Features/Search.feature</FeatureFileResourceName>
      </ReqnrollFeatureFile>
    </ItemGroup>
</Project>
